# Generated by Django 4.2.15 on 2024-08-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["company"],
                "permissions": [("can_view_user", "Can view user")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
