# Generated by Django 4.2.15 on 2024-09-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["company"],
                "permissions": [
                    ("can_block_users", "Can block users"),
                    ("can_view_users", "Can view users"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
