# Generated by Django 4.2.15 on 2024-08-28 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipient",
            name="maill",
        ),
        migrations.AlterField(
            model_name="maill",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Адресаты",
                to="mails.recipient",
                verbose_name="Адресат",
            ),
        ),
    ]
