# Generated by Django 4.2.15 on 2024-08-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0002_remove_recipient_maill_alter_maill_recipient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maill",
            options={
                "ordering": ["title", "recipient", "sent"],
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
    ]
