# Generated by Django 4.2.15 on 2024-08-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0003_alter_maill_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maill",
            name="sent",
            field=models.BooleanField(default=False, verbose_name="Отправлено"),
        ),
    ]
