# Generated by Django 4.2.15 on 2024-08-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0004_alter_maill_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя"
            ),
        ),
    ]
