# Generated by Django 4.2.15 on 2024-08-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0005_alter_recipient_first_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Отправка"),
                ),
                (
                    "event_status",
                    models.CharField(
                        choices=[("failed", "Failed"), ("succeeded", "Succeeded")],
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ответ сервера"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправка",
                "verbose_name_plural": "Отправки",
            },
        ),
        migrations.CreateModel(
            name="Sending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "daily"),
                            ("weekly", "weekly"),
                            ("monthly", "monthly"),
                        ],
                        max_length=15,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("launched", "launched"),
                            ("completed", "completed"),
                        ],
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="maill",
            options={
                "ordering": ["title"],
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.RemoveField(
            model_name="maill",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="maill",
            name="sent",
        ),
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
    ]
