# Generated by Django 4.2.15 on 2024-08-30 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0006_event_sending_alter_maill_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sending",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Название компании",
            ),
        ),
        migrations.AddField(
            model_name="sending",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mails.recipient",
                verbose_name="Почта Адресата",
            ),
        ),
        migrations.AddField(
            model_name="sending",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mails.maill",
                verbose_name="Тема письма",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mails.recipient",
                verbose_name="Email",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mails.sending",
                verbose_name="Тема рассылки",
            ),
        ),
    ]
