# Generated by Django 4.2.15 on 2024-08-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0010_maill_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maill",
            options={
                "ordering": ["title"],
                "permissions": [("can_view_maill", "Can view maill")],
                "verbose_name": "Письмо",
                "verbose_name_plural": "Письма",
            },
        ),
        migrations.AlterModelOptions(
            name="sending",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_view_sending", "Can view sending")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
