# Generated by Django 4.2.15 on 2024-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0011_alter_maill_options_alter_sending_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sending",
            name="email",
        ),
        migrations.AddField(
            model_name="sending",
            name="recipients",
            field=models.ManyToManyField(related_name="sendings", to="mails.recipient"),
        ),
        migrations.AddField(
            model_name="sending",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
