# Generated by Django 4.2.15 on 2024-09-01 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mails", "0012_remove_sending_email_sending_recipients_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "ordering": ["email", "comment"],
                "verbose_name": "Адресат",
                "verbose_name_plural": "Адресаты",
            },
        ),
        migrations.RenameField(
            model_name="event",
            old_name="title",
            new_name="topic",
        ),
        migrations.RenameField(
            model_name="maill",
            old_name="owner",
            new_name="author",
        ),
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="sending",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sendings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
