# Generated by Django 4.2.15 on 2024-09-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0013_alter_recipient_options_rename_title_event_topic_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sending",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_view_sending", "Can view sending"),
                    ("can_disable_sending", "Can disable sending"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
