# Generated by Django 4.2.15 on 2024-09-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0014_alter_sending_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="sending",
            name="is_active",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
