# Generated by Django 4.2.15 on 2024-09-03 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mails", "0015_sending_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
    ]
